### ISSUE TITLE
Update play store icon into the latest one

### ISSUE THREAD

**Issue by Seandylan123** [TeamFiles/Lawnicons#5]
The play store icon is outdated play store recently received a new themed icon

**Comment by Seandylan123** [comment]
![Uploading IMG_20220826_125212.jpg…]()

**Comment by rufus582** [comment]
Updated, thanks

**Comment by Seandylan123** [comment]
> 

![IMG_20220927_145954](https://user-images.githubusercontent.com/106500241/192455866-0a93209e-7e08-49ab-8a06-c584552ac191.jpg)
It's still looks the same you didn't even created a pull request

**Comment by Seandylan123** [comment]
> Well, it will be up in the next update. Should be released hopefully in a couple of days

Are you even a coding developer

**Comment by PalmDevs** [comment]
> > Well, it will be up in the next update. Should be released hopefully in a couple of days
> 
> Are you even a coding developer

If you really want it now, build the app yourself. It's that easy. It seems like you can't though.

**Comment by Seandylan123** [comment]
> > > Well, it will be up in the next update. Should be released hopefully in a couple of days
> > 
> > 
> > Are you even a coding developer
> 
> If you really want it now, build the app yourself. It's that easy. It seems like you can't though. Plus, you don't need a PR when you have write access. Don't act stupid.

I'm not really sure how to make and merge it

**Comment by rufus582** [comment]
> I'm not really sure how to make and merge it

For building, you can clone this repo, then install Android studio and build it from there. There might be another way to just build from terminal, but I'm not sure how it's done.
For merging, just make a PR with ur changes.
